version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.6.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to npm
          command: npm publish
  deploy-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install jsdoc
          command: sudo npm install -g jsdoc
      - run:
          name: Deploy docs
          command: bash scripts/deploy-ghpages.sh

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  test-deploy-docs:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy-docs:
          requires:
            - test
          filters:
            branches:
              only: master
