version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.6.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  deploy:
    <<: *defaults
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  deploy-docs:
    <<: *defaults
    steps:
      - run:
          name: Install JSDoc
          command: npm install -g jsdoc
      - run:
          name: Deploy Docs
          command: bash scripts/deploy-ghpages.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  deploy-docs:
    jobs:
      - deploy-docs:
          filters:
            branches:
              only: master
